# todo-backend: quickstart for backend deployment on OpenShift
:toc:               left
:icons:             font
:idprefix:
:idseparator:       -
:keywords:          openshift,wildfly,microprofile,helm

[abstract]
The `todo-backend` quickstart demonstrates how to implement a backend that exposes a HTTP API with JAX-RS
to manage a list of ToDo which are persisted in a database with JPA.

[WARNING]
This example is using the `wildfly-chart` 1.x. They are not compatible with the `wildfly-chart` 2.x

This quickstart shows how to setup a local deployment of this backend as well as a deployment on OpenShift to connect
to a PostgreSQL database also hosted on OpenShift.

There are two charts to deploy this backend:

* `todo-backend-bootable-jar.yaml` builds and deploys the backend using WildFly Bootable Jar
* `todo-backend-s2i.yaml` builds and deploys the backend using WildFly S2I Builder and Runtime images

Please consult the https://github.com/wildfly/quickstart/blob/master/todo-backend/README.adoc[quickstart's README] for the instructions to use it.
