{{- define "wildfly-common.deployment.tpl" -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "wildfly-common.appName" . }}
  labels: {}
  {{- if and .Values.build.enabled (eq .Values.build.output.kind "ImageStreamTag") }}
  annotations:
    image.openshift.io/triggers: |-
      [
        {
          "from":{
            "kind":"ImageStreamTag",
            "name":"{{ include "wildfly-common.appImage" . }}"
          },
          "fieldPath":"spec.template.spec.containers[0].image"
        }
      ]
  {{- end }}
spec:
  strategy:
    type: Recreate
  replicas: {{ .Values.deploy.replicas }}
  selector:
    matchLabels:
      {{- include "wildfly-common.selectorLabels" . | nindent 6 }}
  {{- include "wildfly-common.podtemplate" . | nindent 2 }}
{{ end }}

{{- define "wildfly-common.deployment" -}}
{{- include "wildfly-common.util.merge" (append . "wildfly-common.deployment.tpl") -}}
{{- end -}}