{{- define "wildfly-common.deployment.tpl" -}}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "wildfly-common.appName" . }}
  labels: {}
  annotations:
  {{- if and .Values.build.enabled (eq .Values.build.output.kind "ImageStreamTag") }}
    image.openshift.io/triggers: |-
      [
        {
          "from":{
            "kind":"ImageStreamTag",
            "name":"{{ include "wildfly-common.appImage" . }}"
          },
          "fieldPath":"spec.template.spec.containers[0].image"
        }
      ]
  {{- end }}
  {{- if and .Values.build.enabled .Values.build.uri }}
    app.openshift.io/vcs-uri:  {{ quote .Values.build.uri }}
  {{- end }}
  {{- if and .Values.build.enabled .Values.build.ref }}
    app.openshift.io/vcs-ref:  {{ quote .Values.build.ref }}
  {{- end }}
  {{- if .Values.deploy.annotations }}
    {{- tpl (toYaml .Values.deploy.annotations) . | nindent 4 }}
  {{- end }}
spec:
  strategy:
    type: Recreate
  replicas: {{ .Values.deploy.replicas }}
  selector:
    matchLabels:
      {{- include "wildfly-common.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: {{ include "wildfly-common.appName" . }}
      labels: {}
      annotations:
      {{- if .Values.deploy.annotations }}
        {{- tpl (toYaml .Values.deploy.annotations) . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.deploy.initContainers }}
      initContainers:
        {{- tpl (toYaml .Values.deploy.initContainers) . | nindent 8 }}
      {{- end }}
      {{- include "wildfly-common.deployment.imagePullSecrets" . | nindent 6 -}}
      containers:
        - name: {{ include "wildfly-common.appName" . }}
          image: {{ include "wildfly-common.appImage" . }}
          {{- if .Values.deploy.argsOverride }}
          args: {{- toYaml .Values.deploy.argsOverride | nindent 12 }}
          {{- end }}
          {{- if .Values.deploy.commandOverride }}
          command: {{- toYaml .Values.deploy.commandOverride | nindent 12 }}
          {{- end }}
          {{- if .Values.deploy.securityContext }}
          securityContext: {{- toYaml .Values.deploy.securityContext | nindent 12 }}
          {{- end }}
          imagePullPolicy: Always
          ports:
          - name: jolokia
            containerPort: 8778
            protocol: TCP
          - name: http
            containerPort: 8080
            protocol: TCP
          - name: ping
            containerPort: 8888
            protocol: TCP
          {{- if .Values.deploy.tls.enabled }}
          - name: https
            containerPort: 8443
            protocol: TCP
          {{- end }}
          - name: admin
            containerPort: 9990
            protocol: TCP
          {{- if .Values.deploy.resources }}
          resources:
            {{- toYaml .Values.deploy.resources | nindent 12 }}
          {{- end }}
          {{- if .Values.deploy.livenessProbe }}
          livenessProbe:
            {{- tpl (toYaml .Values.deploy.livenessProbe) . | nindent 12 }}
          {{- end }}
          {{- if .Values.deploy.readinessProbe }}
          readinessProbe:
            {{- tpl (toYaml .Values.deploy.readinessProbe) . | nindent 12 }}
          {{- end }}
          {{- if .Values.deploy.startupProbe }}
          startupProbe:
            {{- tpl (toYaml .Values.deploy.startupProbe) . | nindent 12 }}
          {{- end }}
          {{- if .Values.deploy.volumeMounts }}
          volumeMounts:
            {{- tpl (toYaml .Values.deploy.volumeMounts) . | nindent 12 }}
          {{- end }}
          env:
          - name: JGROUPS_PING_PROTOCOL
            value: dns.DNS_PING
          - name: OPENSHIFT_DNS_PING_SERVICE_PORT
            value: '8888'
          - name: ENABLE_GENERATE_DEFAULT_DATASOURCE
            value: 'false'
          - name: OPENSHIFT_DNS_PING_SERVICE_NAME
            value: {{ include "wildfly-common.appName" . }}-ping
          - name: ENV_FILES
            value: /etc/extensions/*
          {{- if .Values.deploy.env }}
          {{- tpl (toYaml .Values.deploy.env) . | nindent 10 }}
          {{- end }}
          {{- if .Values.deploy.envFrom }}
          envFrom:
          {{- tpl (toYaml .Values.deploy.envFrom) . | nindent 10 }}
          {{- end }}
        {{- if .Values.deploy.extraContainers }}
        {{- tpl (toYaml .Values.deploy.extraContainers) . | nindent 8 }}
        {{- end }}
      {{- if .Values.deploy.volumes }}
      volumes:
        {{- tpl (toYaml .Values.deploy.volumes) . | nindent 8 }}
      {{- end }}
{{ end }}

{{- define "wildfly-common.deployment" -}}
{{- include "wildfly-common.util.merge" (append . "wildfly-common.deployment.tpl") -}}
{{- end -}}