{{- define "wildfly-common.imagestream-s2i-build-artifacts.tpl" -}}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "wildfly-common.appBuilderImageName" . }}
  labels: {}
{{- end -}}

{{- define "wildfly-common.imagestream-s2i-build-artifacts" -}}
{{- include "wildfly-common.util.merge" (append . "wildfly-common.imagestream-s2i-build-artifacts.tpl") -}}
{{- end -}}